apiVersion: v1
kind: Pod
metadata:
  name: mongo-db-pod
  labels:
    app: mongo
spec:
  containers:
    - name: mongo-container
      image: mongo:latest
      ports:
        - containerPort: 27017
      env:
        - name: MONGO_INITDB_DATABASE
          value: TodoApp