apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: spring-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: spring-app-label
    spec:
      containers:
      - name: spring-container
        image: monicashinde3/spring-mongo:v3
        ports:
        - name: spring-port
          containerPort: 5556
        env:
          - name: MONGO_INITDB_HOST
            value: mongo-service
          - name: MONGO_INITDB_DATABASE
            value: TodoApp
      nodeSelector:
        env: database